### ISSUE TITLE
what to do

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/urlfilter#24]
![image](https://user-images.githubusercontent.com/69903376/133191126-753588f9-0646-4f89-950f-49c715a7d706.png)

**Comment by ameshkov** [comment]
Most likely you're using an old version of golang. Try using the latest one (go 1.17).

**Comment by Karmylr** [comment]
ty

**Comment by Karmylr** [comment]
> Most likely you're using an old version of golang. Try using the latest one (go 1.17).

i installed golang 1.17.1,but the problem is still there.

**Comment by ameshkov** [comment]
Ah, sorry, confused what was written in your screenshot.

There's no `demo.key` file, you need to generate it first.

**Comment by Karmylr** [comment]
> Ah, sorry, confused what was written in your screenshot.
> 
> There's no `demo.key` file, you need to generate it first.

![image](https://user-images.githubusercontent.com/69903376/133227712-1c258c1d-397c-4358-bb44-52afc3938448.png)
i guess i did

**Comment by ameshkov** [comment]
The file name is `root.key`

**Comment by Karmylr** [comment]
> The file name is `root.key`

how to solve "[fatal] failed to load root CA: open root.crt: no such file or directory"

**Comment by ameshkov** [comment]
Make sure that you're using valid path to a file that does exist.

**Comment by Karmylr** [comment]
I tried it again and I did it all according to the readme.md,still have no demo.key

**Comment by Karmylr** [comment]
> Ah, sorry, confused what was written in your screenshot.
> 
> There's no `demo.key` file, you need to generate it first.

I tried it again and I did it all according to the readme.md,still have no demo.key...can u tell me how to generate that?

**Comment by Karmylr** [comment]
> Ah, sorry, confused what was written in your screenshot.
> 
> There's no `demo.key` file, you need to generate it first.

can u tell me how to generate demo.key?

**Comment by EugeneOne1** [comment]
Either rename the `demo.key` to `root.key` with
```
mv demo.key root.key
```
or just use the `demo.key`:
```
openssl req -new -x509 -key demo.key -out root.crt
```

**Comment by Karmylr** [comment]
> Either rename the `demo.key` to `root.key` with
> 
> ```
> mv demo.key root.key
> ```
> 
> or just use the `demo.key`:
> 
> ```
> openssl req -new -x509 -key demo.key -out root.crt
> ```

finally!thank you su much.
