### ISSUE TITLE
amazon.com cant use mitm

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/urlfilter#26]
if use mitm(need replace certificate),amazon will know and 503 error

**Comment by Karmylr** [comment]
||https://amazon.com/rd/uedata?
||https://amazon.com/1/batch/1/OP/
||https://amazon.com/1/remote-weblab-triggers/
||https://amazon.com/$r@https://amazon.com/empty.gif?
||https://amazon.com/rd/uedata?
||https://amazon.com/1/events/
||https://amazon.com/1/batch/1/OE/
||https://amazon.com###nav-swmslot,#sponsoredProducts2_feature_div,.reviews-display-ad

**Comment by Karmylr** [comment]
unless it can be disguised as a certificate similar to amazon's

**Comment by ameshkov** [comment]
Hmm, we'll get to it later when we finally start using this functionality in AdGuard Home.
