### ISSUE TITLE
Youtube Ads Blocking

### ISSUE THREAD

**Issue by deetungsten** [AdguardTeam/urlfilter#33]
Is it possible to block youtube ads with urlfilter? I made a quick docker container to build and run this. Everything works as expected after adding my custom cert and redirecting to the proxy but Youtube is still a hit or miss. Seems like it cuts down on some of the ads but not all. Should I be using a different filter list compared to the ones in the README in the cmd folder? Thank you!

**Comment by ameshkov** [comment]
Nowadays, blocking Youtube ads require using "scriptlet" rules which are not yet implemented by urlfilter.

We're planning to do that later though.
